version: "3.8"

services:

  db:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    ports:
      - ${FAST_API_BACKEND_PORT}:${FAST_API_BACKEND_PORT}
    volumes:
      - ./backend:/app
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port ${FAST_API_BACKEND_PORT}
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    environment:
      VUE_APP_AXIOS_DEFAULT_BASE_URL: ${VUE_APP_AXIOS_DEFAULT_BASE_URL}
    ports:
      - ${VUE_FRONTEND_PORT}:${VUE_FRONTEND_PORT}

volumes:
  postgres_data:
